language: java
jdk: oraclejdk10
before_install:
  - mvn install:install-file -Dfile=lib/yari-core-0.3.1-SNAPSHOT.jar -DgroupId=org.yari -DartifactId=yari-core -Dversion=0.3.1-SNAPSHOT -Dpackaging=jar
jobs:
  include:
    - stage: "Tests"
      script: "mvn clean install -Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
    - stage: "SonarQube"
      if: branch = master
      script: "mvn sonar:sonar -Dsonar.organization=rldiamond-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=0d6954569adf5829df1f616ddbd320e68f6823ff"
after_success:
  - test $TRAVIS_BRANCH = "master" && bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key: $github_token
  file: "target/YariEditor.jar"
  skip_cleanup: true
  on:
    tags: true
