language: java
jdk:
  - oraclejdk10
jobs:
  include:
    - stage: "Tests"
      script: "mvn clean install"
    - stage: "SonarQube"
      script: "mvn sonar:sonar -Dsonar.organization=rldiamond-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=0d6954569adf5829df1f616ddbd320e68f6823ff"
after_success:
  - bash <(curl -s https://codecov.io/bash)
