language: java
jdk: oraclejdk8
before_install:
  - mvn install:install-file -Dfile=lib/yari-core-0.3.4.jar -DgroupId=org.yari -DartifactId=yari-core -Dversion=0.3.4 -Dpackaging=jar
install:
  - mvn clean install -DskipTests=true -B -V
jobs:
  include:
    - stage: "Tests"
      script:
        - mvn test -B -Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500
    - stage: "Sonarqube"
      if: tag IS present
      script: "mvn sonar:sonar -Dsonar.organization=rldiamond-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$sonar_token"
after_success:
  - test $TRAVIS_BRANCH = "master" && bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key: $github_token
  file: "target/YariEditor.jar"
  skip_cleanup: true
  on:
    tags: true
